import { normalizeMediaPresentation } from './model'
import SceneTypeSelector from './SceneTypeSelector'
import LayoutSelector from './LayoutSelector'
import MediaUpload from './MediaUpload'
import MediaLibrary from './MediaLibrary'
export default function PropertiesPanel({scene,onChange,storage,mediaItems,onMediaChanged,usedPaths,onClose}) {
 const update=patch=>onChange({...scene,...patch}), setting=patch=>update({settings:{...scene.settings,...patch}}), content=patch=>update({content:{...scene.content,...patch}}), media=normalizeMediaPresentation(scene.content.media)
 const mediaChange=patch=>content({media:{...media,...patch}})
 const use=item=>content({media:normalizeMediaPresentation({kind:'storage',path:item.storage_path,alt:media.alt||item.title||item.file_name,type:item.mime_type?.startsWith('video/')?'video':'image',mimeType:item.mime_type})})
 const remove=()=>content({media:{kind:'external-url',url:'',alt:''}})
 const key=scene.scene_type==='assignment'?'assignment':'message'
 return <aside className="workshop-properties" aria-label="Szeneneigenschaften"><header><h2>Eigenschaften</h2>{onClose&&<button onClick={onClose} aria-label="Eigenschaften schließen">×</button>}</header><SceneTypeSelector scene={scene} onChange={onChange}/><label>Szenentitel<input value={scene.title} onChange={e=>update({title:e.target.value})}/></label>{scene.scene_type==='narrative'&&<label>Sprecher<input value={scene.content.speaker||''} onChange={e=>content({speaker:e.target.value})}/></label>}<label>{scene.scene_type==='assignment'?'Arbeitsauftrag':'Nachricht'}<textarea rows="5" value={scene.content[key]||''} onChange={e=>content({[key]:e.target.value})}/></label><LayoutSelector value={scene.layout_template} hasImage={!!(media.url||media.path)} onChange={layout_template=>update({layout_template})}/>
 <details open><summary>Darstellung und Medium</summary><label>Textausrichtung<select value={scene.settings.textAlign} onChange={e=>setting({textAlign:e.target.value})}><option value="left">Links</option><option value="center">Zentriert</option></select></label>{scene.scene_type==='transition'&&<label className="check-row"><input type="checkbox" checked={scene.settings.manualContinue} onChange={e=>setting({manualContinue:e.target.checked})}/> Manuellen Weiter-Button zeigen</label>}<label>Alternativtext<input value={media.alt||''} onChange={e=>mediaChange({alt:e.target.value})}/></label><label>Einpassung<select value={media.fit} onChange={e=>mediaChange({fit:e.target.value})}><option value="cover">Fläche füllen</option><option value="contain">Ganzes Medium zeigen</option></select></label><div className="crop-controls"><button type="button" aria-label="Zoom verkleinern" onClick={()=>mediaChange({zoom:Math.max(1,media.zoom-.1)})}>−</button><input aria-label="Zoom" type="range" min="1" max="2" step=".05" value={media.zoom} onChange={e=>mediaChange({zoom:Number(e.target.value)})}/><button type="button" aria-label="Zoom vergrößern" onClick={()=>mediaChange({zoom:Math.min(2,media.zoom+.1)})}>+</button><button type="button" onClick={()=>mediaChange({positionX:50,positionY:50,zoom:1})}>Ausschnitt zurücksetzen</button></div>{media.type==='video'&&<fieldset><legend>Video</legend><label className="check-row"><input type="checkbox" checked={media.autoplay} onChange={e=>mediaChange({autoplay:e.target.checked,muted:e.target.checked?true:media.muted})}/> Automatisch starten (stumm)</label><label className="check-row"><input type="checkbox" checked={media.loop} onChange={e=>mediaChange({loop:e.target.checked})}/> Wiederholen</label><label className="check-row"><input type="checkbox" checked={media.muted} onChange={e=>mediaChange({muted:e.target.checked})}/> Ton aus</label><label className="check-row"><input type="checkbox" checked={media.playback==='manual'} onChange={e=>mediaChange({playback:e.target.checked?'manual':'automatic'})}/> Manuell starten</label></fieldset>}<MediaUpload storage={storage} onUploaded={item=>{onMediaChanged(item);use(item)}}/>{(media.url||media.path)&&<button type="button" onClick={remove}>Medium aus Szene entfernen</button>}<MediaLibrary items={mediaItems} usedPaths={usedPaths} onUse={use} onDelete={async item=>{if(window.confirm(`„${item.title||item.file_name}“ dauerhaft löschen?`)){await storage.remove(item);onMediaChanged()}}}/></details></aside>
}
