import { useState } from 'react'
import { ChevronDown, ChevronUp } from 'lucide-react'
import { normalizeAssignmentSteps, normalizeMediaPresentation } from './model'
import SceneTypeSelector from './SceneTypeSelector'
import LayoutSelector from './LayoutSelector'
import MediaUpload from './MediaUpload'
import MediaLibrary from './MediaLibrary'

export default function PropertiesPanel({scene,onChange,storage,mediaItems,onMediaChanged,usedPaths,onClose}) {
 const [mediaOpen,setMediaOpen]=useState(false)
 const update=patch=>onChange({...scene,...patch}), setting=patch=>update({settings:{...scene.settings,...patch}}), content=patch=>update({content:{...scene.content,...patch}}), media=normalizeMediaPresentation(scene.content.media)
 const mediaChange=patch=>content({media:{...media,...patch}})
 const use=item=>{content({media:normalizeMediaPresentation({kind:'storage',path:item.storage_path,alt:media.alt||item.title||item.file_name,type:item.mime_type?.startsWith('video/')?'video':'image',mimeType:item.mime_type})});setMediaOpen(false)}
 const remove=()=>content({media:{kind:'external-url',url:'',alt:''}})
 const key=scene.scene_type==='assignment'?'assignment':'message', hasMedia=!!(media.url||media.path)
 const steps=normalizeAssignmentSteps(scene.content), updateSteps=next=>content({steps:next})
 const changeStep=(index,value)=>updateSteps(steps.map((step,i)=>i===index?value:step))
 const moveStep=(index,direction)=>{const target=index+direction;if(target<0||target>=steps.length)return;const next=[...steps];[next[index],next[target]]=[next[target],next[index]];updateSteps(next)}
 const speakerLabel={narrative:'Sprecher',assignment:'Auftrag von',transition:'Absender'}[scene.scene_type]
 return <aside className="workshop-properties" aria-label="Szeneneigenschaften"><header><h2>Eigenschaften</h2>{onClose&&<button onClick={onClose} aria-label="Eigenschaften schließen">×</button>}</header><SceneTypeSelector scene={scene} onChange={onChange}/><label>Szenentitel<input value={scene.title} onChange={e=>update({title:e.target.value})}/></label><label>{speakerLabel}<input placeholder="Optional" value={scene.content.speaker||''} onChange={e=>content({speaker:e.target.value})}/></label><label>{scene.scene_type==='assignment'?'Arbeitsauftrag':'Nachricht'}<textarea rows="5" value={scene.content[key]||''} onChange={e=>content({[key]:e.target.value})}/></label>
 {scene.scene_type==='assignment'&&<section className="step-editor"><label className="check-row"><input type="checkbox" checked={!!scene.content.assignmentStepsEnabled} onChange={e=>content({assignmentStepsEnabled:e.target.checked,steps:e.target.checked?steps:scene.content.steps})}/> Auftrag in Schritte gliedern</label>{scene.content.assignmentStepsEnabled&&<><label>Darstellung<select value={scene.content.stepDisplay||'current'} onChange={e=>content({stepDisplay:e.target.value})}><option value="current">Nur aktuellen Schritt zeigen</option><option value="all">Alle Schritte zeigen und aktuellen hervorheben</option></select></label><ol>{steps.map((step,index)=><li key={index}><textarea aria-label={`Arbeitsschritt ${index+1}`} rows="2" value={step} onChange={e=>changeStep(index,e.target.value)}/><div><button type="button" aria-label={`Schritt ${index+1} nach oben`} disabled={index===0} onClick={()=>moveStep(index,-1)}>↑</button><button type="button" aria-label={`Schritt ${index+1} nach unten`} disabled={index===steps.length-1} onClick={()=>moveStep(index,1)}>↓</button><button type="button" disabled={steps.length===1} onClick={()=>updateSteps(steps.filter((_,i)=>i!==index))}>Löschen</button></div></li>)}</ol><button type="button" onClick={()=>updateSteps([...steps,''])}>Schritt hinzufügen</button></>}</section>}
 <LayoutSelector value={scene.layout_template} hasImage={hasMedia} onChange={layout_template=>update({layout_template})}/>
 <details open><summary>Darstellung und Medium</summary><label>Textausrichtung<select value={scene.settings.textAlign||'left'} onChange={e=>setting({textAlign:e.target.value})}><option value="left">Links</option><option value="center">Zentriert</option><option value="right">Rechts</option></select></label>{scene.scene_type==='transition'&&<><label className="check-row"><input type="checkbox" checked={!!scene.content.readiness} onChange={e=>content({readiness:e.target.checked?(scene.content.readiness||'Bereit'):''})}/> Bereitschaft erforderlich</label>{scene.content.readiness&&<label>Beschriftung des Buttons<input value={scene.content.readiness} onChange={e=>content({readiness:e.target.value})}/></label>}<label className="check-row"><input type="checkbox" checked={scene.settings.manualContinue} onChange={e=>setting({manualContinue:e.target.checked})}/> Manuellen Weiter-Button zeigen</label></>}
 <label>Alternativtext<input value={media.alt||''} onChange={e=>mediaChange({alt:e.target.value})}/></label><label>Einpassung<select value={media.fit} onChange={e=>mediaChange({fit:e.target.value})}><option value="cover">Fläche füllen</option><option value="contain">Ganzes Medium zeigen</option></select></label><div className="focus-controls"><label>Horizontaler Fokus<input aria-label="Horizontaler Fokus" type="range" min="0" max="100" value={media.positionX} onChange={e=>mediaChange({positionX:Number(e.target.value)})}/></label><label>Vertikaler Fokus<input aria-label="Vertikaler Fokus" type="range" min="0" max="100" value={media.positionY} onChange={e=>mediaChange({positionY:Number(e.target.value)})}/></label></div><div className="crop-controls"><button type="button" aria-label="Zoom verkleinern" onClick={()=>mediaChange({zoom:Math.max(1,media.zoom-.1)})}>−</button><input aria-label="Zoom" type="range" min="1" max="2" step=".05" value={media.zoom} onChange={e=>mediaChange({zoom:Number(e.target.value)})}/><button type="button" aria-label="Zoom vergrößern" onClick={()=>mediaChange({zoom:Math.min(2,media.zoom+.1)})}>+</button><button type="button" onClick={()=>mediaChange({positionX:50,positionY:50,zoom:1})}>Ausschnitt zurücksetzen</button></div>
 {hasMedia&&<div className="current-medium"><span>Aktuelles Medium: <strong>{media.alt||media.path?.split('/').pop()||media.url?.split('/').pop()||'Medium'}</strong></span><button type="button" onClick={()=>setMediaOpen(true)}>Medium ändern</button><button type="button" onClick={remove}>Medium entfernen</button></div>}
 <section className={`media-accordion ${mediaOpen?'open':''}`}><button type="button" className="media-accordion-toggle" aria-expanded={mediaOpen} onClick={()=>setMediaOpen(value=>!value)}><span>Meine Medien · {mediaItems.length}</span>{mediaOpen?<ChevronUp/>:<ChevronDown/>}</button>{mediaOpen&&<div className="media-accordion-content">{media.type==='video'&&<fieldset><legend>Video</legend><label className="check-row"><input type="checkbox" checked={media.autoplay} onChange={e=>mediaChange({autoplay:e.target.checked,muted:e.target.checked?true:media.muted})}/> Automatisch starten (stumm)</label><label className="check-row"><input type="checkbox" checked={media.loop} onChange={e=>mediaChange({loop:e.target.checked})}/> Wiederholen</label><label className="check-row"><input type="checkbox" checked={media.muted} onChange={e=>mediaChange({muted:e.target.checked})}/> Ton aus</label></fieldset>}<MediaUpload storage={storage} onUploaded={item=>{onMediaChanged(item);use(item)}}/><MediaLibrary items={mediaItems} usedPaths={usedPaths} onUse={use} onDelete={async item=>{if(window.confirm(`„${item.title||item.file_name}“ dauerhaft löschen?`)){await storage.remove(item);onMediaChanged()}}}/></div>}</section></details></aside>
}
