import { useEffect, useMemo, useState } from 'react'
import { ArrowLeft, ArrowRight, Copy, Eye, Plus, Trash2, X } from 'lucide-react'
import { worlds } from '../data'
import { addScene, AUDIENCE_LEVELS, createProject, deleteScene, duplicateScene, moveScene, PROJECT_STATUSES, validateMetadata } from './model'
import { createMissionProjectRepository } from './repository'
import { useAutosave } from './useAutosave'
import SceneRail from './SceneRail'
import ScenePreview from './ScenePreview'
import PropertiesPanel from './PropertiesPanel'

const emptyMetadata = { title: '', description: '', audience_level: 'class-3-6', availability_type: 'free', world_id: worlds[0].id, subject: '', estimated_minutes: '' }

export default function WorkshopApp({ supabase, user, onBack }) {
  const repository = useMemo(() => createMissionProjectRepository(supabase), [supabase])
  const [screen, setScreen] = useState('overview'), [projects, setProjects] = useState([]), [active, setActive] = useState(null), [loading, setLoading] = useState(true), [message, setMessage] = useState('')
  const refresh = async () => { setLoading(true); try { setProjects(await repository.list()); setMessage('') } catch { setMessage('Die Entwürfe konnten nicht geladen werden. Bitte versuche es erneut.') } finally { setLoading(false) } }
  useEffect(() => { refresh() }, [repository])
  const open = async (id, preview = false) => { setLoading(true); try { setActive(await repository.load(id)); setScreen(preview ? 'preview' : 'editor') } catch { setMessage('Dieser Entwurf konnte nicht geöffnet werden.') } finally { setLoading(false) } }
  if (screen === 'new') return <MetadataForm onCancel={()=>setScreen('overview')} onCreate={async metadata=>{ try { const created=await repository.create({ ...createProject(metadata), owner_id:user.id }); setActive(created); setScreen('editor') } catch { setMessage('Die Mission konnte nicht angelegt werden.') } }}/>
  if (screen === 'editor' && active) return <MissionEditor project={active} repository={repository} onChange={setActive} onClose={()=>{setScreen('overview');refresh()}} onPreview={()=>setScreen('preview')}/>
  if (screen === 'preview' && active) return <PreviewMode project={active} onBack={()=>setScreen('editor')}/>
  return <main className="workshop-home"><header className="workshop-title"><div><button className="text-button" onClick={onBack}><ArrowLeft/> Zur Lehrerübersicht</button><span className="kicker">MISSIONEN GESTALTEN</span><h1><span aria-hidden="true">Lore-</span>Werkstatt</h1><p>Erschaffe Missionen aus klar aufgebauten Szenen.</p></div><button className="btn gold" onClick={()=>setScreen('new')}><Plus/> Neue Mission</button></header>{message&&<p className="workshop-error" role="alert">{message}</p>}{loading?<p role="status">Entwürfe werden geladen …</p>:projects.length===0?<section className="workshop-empty"><span>✦</span><h2>Deine erste Mission wartet</h2><p>Beginne mit einem Entwurf und führe deine Klasse Szene für Szene durch ein neues Lernabenteuer.</p><button className="btn dark" onClick={()=>setScreen('new')}><Plus/> Erste Mission erstellen</button></section>:<section className="project-grid" aria-label="Eigene Missionsentwürfe">{projects.map(project=><article key={project.id}><span className={`project-status status-${project.status}`}>{PROJECT_STATUSES[project.status]}</span><h2>{project.title}</h2><p>{project.description || 'Noch keine Beschreibung'}</p><small>Zuletzt bearbeitet: {new Intl.DateTimeFormat('de-DE',{dateStyle:'medium',timeStyle:'short'}).format(new Date(project.updated_at))}</small><div><button onClick={()=>open(project.id)}><ArrowRight/> Bearbeiten</button><button onClick={()=>open(project.id,true)}><Eye/> Vorschau</button><button onClick={async()=>{await repository.duplicate(project.id);refresh()}}><Copy/> Duplizieren</button><button onClick={async()=>{if(window.confirm(`„${project.title}“ wirklich löschen? Diese Aktion kann nicht rückgängig gemacht werden.`)){await repository.remove(project.id);refresh()}}}><Trash2/> Löschen</button></div></article>)}</section>}</main>
}

function MetadataForm({ onCancel, onCreate }) {
  const [value,setValue]=useState(emptyMetadata), [errors,setErrors]=useState({}), [busy,setBusy]=useState(false)
  const set=(key,next)=>setValue(current=>({...current,[key]:next}))
  const submit=async event=>{event.preventDefault();const next=validateMetadata(value);setErrors(next);if(Object.keys(next).length)return;setBusy(true);await onCreate(value);setBusy(false)}
  return <main className="metadata-page"><form className="metadata-form" onSubmit={submit}><header><button type="button" className="text-button" onClick={onCancel}><X/> Abbrechen</button><span className="kicker">NEUER ENTWURF</span><h1>Neue Mission</h1><p>Lege zuerst den klaren Rahmen fest. Details gestaltest du anschließend Szene für Szene.</p></header><label>Missionstitel<input autoFocus value={value.title} onChange={e=>set('title',e.target.value)} aria-invalid={!!errors.title}/>{errors.title&&<small role="alert">{errors.title}</small>}</label><label>Kurze Beschreibung<textarea rows="3" value={value.description} onChange={e=>set('description',e.target.value)}/></label><div className="form-row"><label>Zielgruppe<select value={value.audience_level} onChange={e=>set('audience_level',e.target.value)}>{Object.entries(AUDIENCE_LEVELS).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>Geschätzte Dauer (Minuten)<input type="number" min="1" max="600" value={value.estimated_minutes} onChange={e=>set('estimated_minutes',e.target.value)}/>{errors.estimated_minutes&&<small role="alert">{errors.estimated_minutes}</small>}</label></div><fieldset><legend>Zuordnung</legend><label><input type="radio" name="availability" checked={value.availability_type==='free'} onChange={()=>set('availability_type','free')}/> Freie Mission – aus jeder Welt abrufbar</label><label><input type="radio" name="availability" checked={value.availability_type==='world'} onChange={()=>set('availability_type','world')}/> Weltmission</label></fieldset>{value.availability_type==='world'&&<label>Welt<select value={value.world_id} onChange={e=>set('world_id',e.target.value)}>{worlds.map(world=><option key={world.id} value={world.id}>{world.name}</option>)}</select></label>}<label>Fach (optional)<input value={value.subject} onChange={e=>set('subject',e.target.value)}/></label><button className="btn gold full" disabled={busy}>{busy?'Wird angelegt …':'Mission anlegen'}</button></form></main>
}

function MissionEditor({ project, repository, onChange, onClose, onPreview }) {
  const [selected,setSelected]=useState(0), [leftOpen,setLeftOpen]=useState(true), [rightOpen,setRightOpen]=useState(true)
  const {status,error,dirty}=useAutosave(project,repository)
  const scenes=project.scenes, scene=scenes[selected] || scenes[0]
  const changeScene=next=>onChange({...project,scenes:scenes.map((item,index)=>index===selected?next:item)})
  const close=()=>{if(dirty&&!window.confirm('Es gibt noch nicht gespeicherte Änderungen. Werkstatt trotzdem verlassen?'))return;onClose()}
  return <main className="mission-editor"><header className="editor-top"><button onClick={close}><ArrowLeft/> Werkstatt</button><input aria-label="Missionsname" value={project.title} onChange={e=>onChange({...project,title:e.target.value})}/><span className={`save-status save-${status.replaceAll(' ','-')}`}>{status}</span><button onClick={onPreview}><Eye/> Vorschau</button></header>{error&&<p className="editor-save-error" role="alert">{error}</p>}<div className="tablet-panel-toggles"><button aria-pressed={leftOpen} onClick={()=>setLeftOpen(x=>!x)}>Szenen</button><button aria-pressed={rightOpen} onClick={()=>setRightOpen(x=>!x)}>Eigenschaften</button></div><div className={`editor-shell ${leftOpen?'left-open':''} ${rightOpen?'right-open':''}`}>
    {leftOpen&&<SceneRail scenes={scenes} selected={selected} onSelect={setSelected} onAdd={()=>{onChange({...project,scenes:addScene(scenes)});setSelected(scenes.length)}} onDuplicate={index=>{onChange({...project,scenes:duplicateScene(scenes,index)});setSelected(index+1)}} onDelete={index=>{onChange({...project,scenes:deleteScene(scenes,index)});setSelected(Math.max(0,Math.min(selected,scenes.length-2)))}} onMove={(index,direction)=>{onChange({...project,scenes:moveScene(scenes,index,direction)});setSelected(index+direction)}}/>}
    <section className="scene-workspace"><p className="mobile-workshop-note">Die Lore-Werkstatt ist für größere Displays optimiert. Auf diesem Gerät steht die Vorschau im Mittelpunkt.</p><ScenePreview scene={scene} editing onChange={changeScene}/></section>
    {rightOpen&&<PropertiesPanel scene={scene} onChange={changeScene}/>}</div></main>
}

function PreviewMode({project,onBack}) { const [index,setIndex]=useState(0), [size,setSize]=useState('desktop'); return <main className="preview-mode"><header><button onClick={onBack}><ArrowLeft/> Zurück zum Editor</button><strong>{project.title}</strong><div>{['desktop','beamer','ipad'].map(item=><button className={size===item?'active':''} key={item} onClick={()=>setSize(item)}>{item==='ipad'?'iPad':item[0].toUpperCase()+item.slice(1)}</button>)}</div></header><section className="preview-stage"><ScenePreview scene={project.scenes[index]} size={size}/></section><footer><button disabled={index===0} onClick={()=>setIndex(i=>i-1)}><ArrowLeft/> Zurück</button><span>{index+1} / {project.scenes.length}</span><button disabled={index===project.scenes.length-1} onClick={()=>setIndex(i=>i+1)}>Weiter <ArrowRight/></button></footer></main> }
