import { useEffect, useState } from 'react'
import { ArrowRight, BookOpen, Check, ChevronDown, CirclePlay, Compass, Feather, Gem, Library, LogOut, Menu, PenLine, Plus, Search, ShoppingBag, Sparkles, WandSparkles, X } from 'lucide-react'
import { stories, worlds } from './data'
import { addStoryToFundus, readState } from './state'

function App() {
  const [initial] = useState(() => readState(localStorage))
  const [loggedIn, setLoggedIn] = useState(initial.loggedIn)
  const [view, setView] = useState(initial.view)
  const [fundus, setFundus] = useState(initial.fundus)
  const [activeStory, setActiveStory] = useState(initial.activeStory)
  const [activeWorld, setActiveWorld] = useState(initial.activeWorld)
  const [toast, setToast] = useState('')
  useEffect(() => localStorage.setItem('lore-state', JSON.stringify({ loggedIn, view, fundus, activeStory, activeWorld })), [loggedIn, view, fundus, activeStory, activeWorld])
  const notify = (text) => { setToast(text); window.setTimeout(() => setToast(''), 2600) }
  if (!loggedIn) return <Landing onLogin={() => setLoggedIn(true)} />
  return <Platform {...{ view, setView, fundus, setFundus, activeStory, setActiveStory, activeWorld, setActiveWorld, notify }} onLogout={() => setLoggedIn(false)} toast={toast} />
}

function Brand({ light = false }) { return <div className={`brand ${light ? 'brand-light' : ''}`}><span className="brand-mark"><Feather size={20} /></span><span>LORE <b>STORY</b></span></div> }

function Landing({ onLogin }) {
  const [loginOpen, setLoginOpen] = useState(false)
  return <main className="landing">
    <header className="public-nav"><Brand light /><nav><a href="#welten">Welten</a><a href="#features">So funktioniert’s</a><button className="btn ghost" onClick={() => setLoginOpen(true)}>Einloggen</button><button className="btn gold" onClick={() => setLoginOpen(true)}>Kostenlos starten <ArrowRight size={16} /></button></nav></header>
    <section className="hero">
      <div className="stars" /><div className="hero-orb orb-a"/><div className="hero-orb orb-b"/>
      <div className="hero-copy"><div className="eyebrow"><Sparkles size={14}/> Geschichten, die Wissen lebendig machen</div><h1><span>Lernen wird</span><br/>zur <em>Legende.</em></h1><p>Verwandle Lerninhalte in interaktive Abenteuer. Erschaffe Welten, in denen Neugier den Weg weist und jedes Kapitel neues Wissen entfacht.</p><div className="hero-actions"><button className="btn gold large" onClick={() => setLoginOpen(true)}>Dein Abenteuer beginnt <ArrowRight size={18}/></button><a className="text-link" href="#welten"><CirclePlay size={20}/> Welten entdecken</a></div><div className="trust"><span>✦ Für Lehrkräfte</span><span>✦ Für Lernende</span><span>✦ Für kreative Köpfe</span></div></div>
      <div className="hero-scene" aria-label="Illustrative Vorschau einer Lore-Welt"><div className="moon"/><div className="mountain m1"/><div className="mountain m2"/><div className="floating-card"><span>Aktives Abenteuer</span><b>Das Flüstern des<br/>Moosarchivs</b><small>Kapitel 2 von 5</small><i><u style={{width:'38%'}}/></i></div></div>
    </section>
    <section id="welten" className="section worlds-section"><div className="section-heading"><div><span className="kicker">DEINE REISE. DEINE WELT.</span><h2>Wo Wissen Geschichten schreibt</h2></div><p>Jede Welt ist ein Tor zu neuen Perspektiven. Die Lernziele bleiben – das Abenteuer passt sich dir an.</p></div><div className="world-grid">{worlds.map((w,i)=><article className="world-card" key={w.id} style={{'--c1':w.colors[0],'--c2':w.colors[1]}}><div className="world-art"><span className="world-num">0{i+1}</span><i>{w.icon}</i></div><div className="world-copy"><small>{w.label}</small><h3>{w.name}</h3><p>{w.description}</p><button>Welt erkunden <ArrowRight size={16}/></button></div></article>)}</div></section>
    <section id="features" className="section feature-section"><div className="feature-intro"><span className="kicker">EINE IDEE. UNENDLICHE WEGE.</span><h2>Vom Lernziel<br/>zum Abenteuer.</h2><p>Alles, was du brauchst, um Wissen in Geschichten zu verwandeln – intuitiv, flexibel und voller Magie.</p></div><div className="feature-list">{[[WandSparkles,'Geschichten gestalten','Baue verzweigte Lernabenteuer mit Szenen, Aufgaben und Entscheidungen.'],[Library,'Wissen sammeln','Entdecke erprobte Stories im Lore-Market und organisiere sie in deinem Fundus.'],[Compass,'Welten wechseln','Übertrage eine Lernstruktur mit einem Klick in ein völlig neues Universum.']].map(([I,t,d],i)=><div className="feature" key={t}><span>0{i+1}</span><I/><div><h3>{t}</h3><p>{d}</p></div></div>)}</div></section>
    <footer><Brand light/><p>Geschichten öffnen Türen. Wissen zeigt den Weg.</p><small>© 2026 Lore Story · Ein Prototyp für neugierige Menschen</small></footer>
    {loginOpen && <LoginModal onClose={()=>setLoginOpen(false)} onLogin={onLogin}/>}
  </main>
}

function LoginModal({ onClose, onLogin }) { const [register,setRegister]=useState(false); return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="login-modal"><button className="modal-close" onClick={onClose}><X/></button><Brand/><span className="kicker">WILLKOMMEN IN DER WERKSTATT</span><h2>{register?'Deine Geschichte beginnt.':'Schön, dass du wieder da bist.'}</h2><p>{register?'Erschaffe deinen kostenlosen Lore-Zugang.':'Melde dich an und setze dein Abenteuer fort.'}</p><label>E-Mail-Adresse<input type="email" defaultValue="demo@lore-story.de"/></label><label>Passwort<input type="password" defaultValue="lorestory"/></label><button className="btn dark large full" onClick={onLogin}>{register?'Konto erstellen':'In die Lore-Werkstatt'} <ArrowRight size={17}/></button><div className="demo-note"><Sparkles size={15}/><span><b>Demo-Modus</b><br/>Beliebige Zugangsdaten funktionieren.</span></div><button className="switch-auth" onClick={()=>setRegister(!register)}>{register?'Bereits dabei? Einloggen':'Noch nicht dabei? Kostenlos registrieren'}</button></div></div> }

const navItems = [['loreboard',BookOpen,'Loreboard'],['werkstatt',PenLine,'Werkstatt'],['fundus',Gem,'Fundus'],['market',ShoppingBag,'Lore-Market'],['weltwechsler',Compass,'Weltwechsler']]

function Platform(props) {
  const {view,setView,onLogout,toast}=props; const [mobile,setMobile]=useState(false)
  const go=(v)=>{setView(v);setMobile(false)}
  return <div className="platform"><aside className={mobile?'open':''}><div className="aside-head"><Brand light/><button className="mobile-close" onClick={()=>setMobile(false)}><X/></button></div><div className="workspace-label">MEINE LORE-WERKSTATT</div><nav>{navItems.map(([id,I,label])=><button className={view===id?'active':''} key={id} onClick={()=>go(id)}><I size={19}/>{label}{label==='Lore-Market'&&<span className="new-pill">NEU</span>}</button>)}</nav><div className="aside-world"><small>AKTIVE WELT</small><div><span>✦</span><b>{worlds.find(w=>w.id===props.activeWorld)?.name}</b></div></div><button className="profile" onClick={onLogout}><span>LS</span><div><b>Lea Schneider</b><small>Kreativkonto</small></div><LogOut size={17}/></button></aside>
    <main className="app-main"><header className="app-top"><button className="menu-btn" onClick={()=>setMobile(true)}><Menu/></button><div><span className="breadcrumb">LORE STORY /</span> {navItems.find(n=>n[0]===view)?.[2]}</div><div className="top-actions"><button className="icon-btn"><Search size={19}/></button><button className="avatar">LS</button></div></header><div className="view">{view==='loreboard'&&<Loreboard {...props}/>} {view==='werkstatt'&&<Workshop {...props}/>} {view==='fundus'&&<Fundus {...props}/>} {view==='market'&&<Market {...props}/>} {view==='weltwechsler'&&<WorldSwitcher {...props}/>}</div></main>{toast&&<div className="toast"><Check size={17}/>{toast}</div>}</div>
}

function PageHead({ kicker,title,copy,action }) { return <div className="page-head"><div><span className="kicker">{kicker}</span><h1>{title}</h1><p>{copy}</p></div>{action}</div> }
function Loreboard({fundus,activeStory,setActiveStory,setView,activeWorld,notify}) { const available=stories.filter(s=>fundus.includes(s.id)); const story=stories.find(s=>s.id===activeStory)||available[0]; const world=worlds.find(w=>w.id===activeWorld); return <><PageHead kicker="GUTEN MORGEN, LEA" title="Dein Loreboard" copy="Hier beginnt jede große Geschichte. Was möchtest du heute entdecken?" action={<button className="btn dark" onClick={()=>setView('market')}><Plus size={17}/> Story entdecken</button>}/><div className="active-banner" style={{'--accent':world.colors[0]}}><div className="banner-copy"><span className="status"><i/> BEREIT FÜR DEIN ABENTEUER</span><small>{world.name} · {story.subject}</small><h2>{story.title}</h2><p>{story.description}</p><div className="progress-row"><span>Dein Fortschritt</span><b>Kapitel 2 / {story.chapters}</b></div><div className="progress"><i style={{width:`${200/story.chapters}%`}}/></div><div className="banner-actions"><button className="btn gold" onClick={()=>notify('Abenteuer gestartet – Kapitel 2 wird geladen')}><CirclePlay size={18}/> Abenteuer fortsetzen</button><button className="btn glass" onClick={()=>setView('werkstatt')}><PenLine size={17}/> Bearbeiten</button></div></div><div className="banner-symbol">{world.icon}</div></div><section className="dashboard-section"><div className="section-title"><div><h3>Aus deinem Fundus</h3><p>Wähle eine aktive Story für dein Loreboard.</p></div><button onClick={()=>setView('fundus')}>Alle anzeigen <ArrowRight size={16}/></button></div><div className="story-row">{available.map(s=><StoryCard key={s.id} story={s} active={s.id===activeStory} action={()=>{setActiveStory(s.id);notify('Story im Loreboard aktiviert')}}/>)}</div></section></> }
function StoryCard({story,action,active,market=false,owned=false}) { const w=worlds.find(x=>x.id===story.world); return <article className="story-card"><div className="story-visual" style={{'--accent':story.accent}}><span>{w.icon}</span><small>{w.name}</small>{active&&<b className="active-tag"><Check size={12}/> AKTIV</b>}</div><div className="story-info"><div className="chips"><span>{story.subject}</span><span>{story.age} Jahre</span></div><h3>{story.title}</h3><p>{story.description}</p><div className="story-meta"><span><BookOpen size={14}/>{story.chapters} Kapitel</span><span>◷ {story.duration}</span></div><button className={active?'selected':''} disabled={owned&&market} onClick={action}>{market?(owned?<><Check/> Im Fundus</>:<><Plus/> Zum Fundus</>):active?'Aktive Story':'Im Loreboard aktivieren'}</button></div></article> }
function Fundus({fundus,activeStory,setActiveStory,setView,notify}) { const list=stories.filter(s=>fundus.includes(s.id)); return <><PageHead kicker="DEINE SAMMLUNG" title="Fundus" copy="Alle Geschichten, die du gesammelt hast – bereit für ihr nächstes Abenteuer." action={<button className="btn dark" onClick={()=>setView('market')}><ShoppingBag size={17}/> Lore-Market öffnen</button>}/><div className="filterbar"><b>{list.length} Geschichten</b><div><button className="filter-active">Alle</button><button>Eigene</button><button>Gesammelt</button></div></div><div className="story-grid">{list.map(s=><StoryCard key={s.id} story={s} active={s.id===activeStory} action={()=>{setActiveStory(s.id);notify('Story aktiviert und ins Loreboard gelegt')}}/>)}</div></> }
function Market({fundus,setFundus,notify}) { const add=id=>{const next=addStoryToFundus(fundus,id);if(next!==fundus){setFundus(next);notify('Story wurde deinem Fundus hinzugefügt')}}; return <><PageHead kicker="GESCHICHTEN, DIE INSPIRIEREN" title="Lore-Market" copy="Entdecke handverlesene Lernabenteuer und mache sie zu deinen eigenen."/><div className="market-hero"><div><span>EMPFEHLUNG DER WOCHE</span><h2>Entdecke das geheime<br/>Netzwerk des Waldes.</h2><p>Ein biologisches Lernabenteuer über Symbiosen, Pilze und die Sprache der Bäume.</p></div><Sparkles/></div><div className="filterbar"><b>Für dich ausgewählt</b><div><button className="filter-active">Alle Fächer</button><button>Mathematik</button><button>Sprachen</button><button>Natur</button></div></div><div className="story-grid">{stories.map(s=><StoryCard key={s.id} story={s} market owned={fundus.includes(s.id)} action={()=>add(s.id)}/>)}</div></> }
function Workshop({activeStory,notify}) { const story=stories.find(s=>s.id===activeStory); const [title,setTitle]=useState(story.title); const [desc,setDesc]=useState(story.description); useEffect(()=>{setTitle(story.title);setDesc(story.description)},[story]); return <><PageHead kicker="GESCHICHTEN SCHREIBEN" title="Werkstatt" copy="Forme deine Lore. Jede Änderung wird Teil deines nächsten Abenteuers." action={<button className="btn dark" onClick={()=>notify('Deine Änderungen wurden lokal gespeichert')}><Check size={17}/> Änderungen speichern</button>}/><div className="editor-layout"><div className="editor-card"><div className="editor-tabs"><button className="active">Grundlagen</button><button>Kapitel & Szenen</button><button>Lernziele</button></div><label>Titel der Story<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Kurzbeschreibung<textarea rows="4" value={desc} onChange={e=>setDesc(e.target.value)}/></label><div className="form-row"><label>Fach<select defaultValue={story.subject}><option>{story.subject}</option><option>Mathematik</option><option>Deutsch</option></select></label><label>Altersgruppe<select defaultValue={story.age}><option>{story.age}</option><option>8–11</option><option>12–15</option></select></label></div></div><aside className="chapter-list"><div><span>STORY-STRUKTUR</span><b>{story.chapters} Kapitel</b></div>{Array.from({length:story.chapters},(_,i)=><button className={i===1?'active':''} key={i}><span>0{i+1}</span><div><b>{['Der Ruf des Waldes','Unter dem Wurzelmeer','Das verborgene Geflecht','Die Prüfung der Hüter','Ein neuer Morgen','Die letzte Karte'][i]}</b><small>{i===1?'In Bearbeitung':'Entwurf'}</small></div><ChevronDown size={15}/></button>)}<button className="add-chapter"><Plus size={16}/> Kapitel hinzufügen</button></aside></div></> }
function WorldSwitcher({activeStory,activeWorld,setActiveWorld,notify}) { const story=stories.find(s=>s.id===activeStory); return <><PageHead kicker="GLEICHE STRUKTUR. NEUE MAGIE." title="Weltwechsler" copy="Übertrage deine Geschichte in eine andere Welt. Lernziele und Dramaturgie bleiben erhalten."/><div className="switch-panel"><div className="switch-story"><span>AKTUELLE STORY</span><h3>{story.title}</h3><p>{story.subject} · {story.chapters} Kapitel · {story.age} Jahre</p></div><div className="switch-arrow"><WandSparkles/></div><div><span className="kicker">ZIELWELT WÄHLEN</span><div className="world-options">{worlds.map(w=><button className={activeWorld===w.id?'active':''} onClick={()=>setActiveWorld(w.id)} key={w.id} style={{'--world':w.colors[0]}}><i>{w.icon}</i><div><b>{w.name}</b><small>{w.label}</small></div>{activeWorld===w.id&&<Check/>}</button>)}</div></div></div><div className="transfer-preview"><div><span>VORHER</span><h3>{story.title}</h3><p>Ein geheimnisvolles Netzwerk muss verstanden werden, um das Gleichgewicht wiederherzustellen.</p></div><ArrowRight/><div><span>NACHHER · {worlds.find(w=>w.id===activeWorld).name.toUpperCase()}</span><h3>{activeWorld==='aether'?'Das Echo der Himmelsarchive':activeWorld==='tiefsee'?'Das Leuchten der Tiefenchronik':story.title}</h3><p>Die Lernstruktur bleibt identisch – Figuren, Schauplätze und Atmosphäre werden neu inszeniert.</p></div></div><button className="btn gold switch-submit" onClick={()=>notify(`Story erfolgreich nach ${worlds.find(w=>w.id===activeWorld).name} übertragen`)}><Sparkles size={17}/> Weltwechsel anwenden</button></> }

export default App
