import { useEffect, useRef, useState } from 'react'
import { Check, Radio, Rocket, Wifi, WifiOff } from 'lucide-react'
import { missionErrorMessage } from './mission'

export default function JoinMission({ supabase, code }) {
 const normalized=code.trim().toUpperCase(); const [screen,setScreen]=useState('loading'); const [info,setInfo]=useState(null); const [chosen,setChosen]=useState(''); const [message,setMessage]=useState(''); const [online,setOnline]=useState(window.navigator.onLine); const cleanup=useRef(()=>{})
 const inspect=async()=>{setMessage('');try{let {data:{session}}=await supabase.auth.getSession();if(!session?.user?.is_anonymous){const result=await supabase.auth.signInAnonymously();if(result.error)throw result.error}const {data,error}=await supabase.rpc('inspect_mission',{p_code:normalized});if(error)throw error;setInfo(data?.[0]);setScreen('choose')}catch(e){setMessage(missionErrorMessage(e));setScreen('error')}}
 useEffect(()=>{inspect();const on=()=>setOnline(true),off=()=>setOnline(false);window.addEventListener('online',on);window.addEventListener('offline',off);return()=>{window.removeEventListener('online',on);window.removeEventListener('offline',off);cleanup.current()}},[])
 const listen=(sessionId,participantId)=>{cleanup.current();const channel=supabase.channel(`student:${sessionId}`).on('postgres_changes',{event:'UPDATE',schema:'public',table:'mission_sessions',filter:`id=eq.${sessionId}`},payload=>setInfo(x=>({...x,...payload.new}))).on('postgres_changes',{event:'UPDATE',schema:'public',table:'mission_participants',filter:`id=eq.${participantId}`},payload=>{if(payload.new.status==='removed'){setMessage(missionErrorMessage({message:'PARTICIPANT_REMOVED'}));setScreen('removed')}}).subscribe(status=>setOnline(status==='SUBSCRIBED'));cleanup.current=()=>supabase.removeChannel(channel)}
 const join=async(callsign=chosen)=>{if(!callsign)return;setMessage('');try{const {data,error}=await supabase.rpc('join_mission',{p_code:normalized,p_callsign:callsign});if(error)throw error;const joined=data?.[0];setInfo(joined);setChosen(joined.callsign);localStorage.setItem(`mission-callsign:${normalized}`,joined.callsign);setScreen('waiting');listen(joined.session_id,joined.participant_id)}catch(e){setMessage(missionErrorMessage(e));await inspect()}}
 useEffect(()=>{if(screen==='choose'){const saved=localStorage.getItem(`mission-callsign:${normalized}`);if(saved){setChosen(saved);join(saved)}}},[screen])
 const ready=async readyValue=>{const {error}=await supabase.rpc('update_my_mission_presence',{p_session_id:info.session_id,p_connected:true,p_ready:readyValue});if(error)setMessage(missionErrorMessage(error));else setInfo(x=>({...x,ready_scene_id:readyValue?x.current_scene_id:null}))}
 if(screen==='loading')return <main className="join-page"><div className="join-card"><Rocket/><h1>Mission wird gesucht …</h1></div></main>
 if(screen==='error'||screen==='removed')return <main className="join-page"><div className="join-card"><WifiOff/><h1>Zugang nicht möglich</h1><p role="alert">{message}</p>{screen==='error'&&<button onClick={inspect}>Erneut versuchen</button>}</div></main>
 if(screen==='choose')return <main className="join-page"><div className="join-card wide"><Rocket/><small>LORE ASTRA</small><h1>{info.title}</h1><p>Wähle dein anonymes Rufzeichen. Es werden keine Namen benötigt.</p><div className="callsign-grid">{info.callsigns.map(name=><button key={name} disabled={info.taken_callsigns.includes(name)} className={chosen===name?'selected':''} onClick={()=>setChosen(name)}>{name}{info.taken_callsigns.includes(name)&&<small>belegt</small>}</button>)}</div>{message&&<p role="alert">{message}</p>}<button className="primary" disabled={!chosen||!info.joining_open} onClick={join}>Mit {chosen||'Rufzeichen'} beitreten</button></div></main>
 const active=info.status==='active'||info.status==='paused',completed=info.status==='completed'
 return <main className="join-page"><div className="join-card"><div className={`connection ${online?'online':''}`}>{online?<Wifi/>:<WifiOff/>}{online?'Verbunden':'Verbindung unterbrochen'}</div><Rocket/><small>DEIN RUFZEICHEN</small><h1>{chosen}</h1><h2>{info.title}</h2>{completed?<p>Die Mission ist abgeschlossen. Danke für deinen Einsatz!</p>:active?<><p>Die Missionssitzung ist aktiv. Die Storyoberfläche wird im nächsten Entwicklungsschritt angebunden.</p><button className="primary" onClick={()=>ready(!info.ready_scene_id)}>{info.ready_scene_id?<><Check/> Nicht mehr bereit</>:<><Radio/> Ich bin bereit</>}</button></>:<p>Warte bitte, bis die Lehrkraft die Mission startet.</p>}{message&&<p role="alert">{message}</p>}</div></main>
}
