import { useEffect, useMemo, useState } from 'react'
import QRCode from 'qrcode'
import { ArrowLeft, Check, Play, Radio, RefreshCw, Trash2, Wifi, WifiOff, X } from 'lucide-react'
import { createMissionRepository, readyCount, STORY_TITLE } from './mission'
export default function MissionLobby({supabase,user,onBack}) {
 const repo=useMemo(()=>createMissionRepository(supabase,user),[supabase,user]);const [session,setSession]=useState(null),[participants,setParticipants]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[online,setOnline]=useState(true),[qr,setQr]=useState('')
 const refresh=async()=>{try{const rows=await repo.list();const current=rows.find(x=>x.status!=='completed')||rows[0]||null;setSession(current);setParticipants(current?await repo.participants(current.id):[]);setError('')}catch{setError('Die Missionsdaten konnten nicht geladen werden.')}finally{setLoading(false)}}
 useEffect(()=>{refresh()},[])
 useEffect(()=>session?repo.subscribe(session.id,refresh,status=>setOnline(status==='SUBSCRIBED')):undefined,[session?.id])
 useEffect(()=>{if(session)QRCode.toDataURL(`${window.location.origin}/join/${session.join_code}`,{width:320,margin:1,color:{dark:'#10243d',light:'#ffffff'}}).then(setQr)},[session?.id])
 const create=async()=>{setLoading(true);try{setSession(await repo.create());setParticipants([])}catch{setError('Die Mission konnte nicht vorbereitet werden.')}finally{setLoading(false)}}
 const patch=async value=>{try{setSession(await repo.update(session.id,value))}catch{setError('Die Änderung konnte nicht gespeichert werden.')}}
 const begin=()=>window.confirm('Mission jetzt manuell beginnen?')&&patch({status:'active',joining_open:false,started_at:new Date().toISOString(),current_scene_id:'testszene'})
 const finish=()=>window.confirm('Mission wirklich abschließen? Danach kann sie nicht mehr verändert werden.')&&patch({status:'completed',joining_open:false,completed_at:new Date().toISOString()})
 if(loading)return <main className="mission-lobby"><p>Mission wird geladen …</p></main>
 if(!session)return <main className="mission-lobby"><button className="back" onClick={onBack}><ArrowLeft/> Zum Loreboard</button><section className="empty-mission"><small>LORE ASTRA</small><h1>{STORY_TITLE}</h1><p>Bereite eine sichere Sitzung mit anonymen Rufzeichen vor.</p>{error&&<p role="alert">{error}</p>}<button className="primary" onClick={create}>Mission vorbereiten</button></section></main>
 const activeParticipants=participants.filter(p=>p.status!=='removed');const ready=readyCount(activeParticipants,session.current_scene_id);const missing=activeParticipants.filter(p=>p.ready_scene_id!==session.current_scene_id)
 return <main className="mission-lobby"><header><button className="back" onClick={onBack}><ArrowLeft/> Zum Loreboard</button><div className={`connection ${online?'online':''}`}>{online?<Wifi/>:<WifiOff/>}{online?'Realtime verbunden':'Verbindung unterbrochen'}</div></header><section className="mission-title"><small>LORE ASTRA · {session.status==='lobby'?'MISSIONSLOBBY':session.status==='completed'?'ARCHIV':'AKTIVE MISSION'}</small><h1>{session.title}</h1></section><div className="mission-layout"><article className="join-panel">{qr&&<img src={qr} alt={`QR-Code für Sitzung ${session.join_code}`}/>}<span>SITZUNGSCODE</span><strong>{session.join_code}</strong><p>{window.location.origin}/join/{session.join_code}</p><button onClick={()=>patch({joining_open:!session.joining_open})} disabled={session.status==='completed'}>{session.joining_open?<><X/> Zugang schließen</>:<><RefreshCw/> Zugang öffnen</>}</button></article><article className="crew-panel"><div><span>CREW</span><strong>{activeParticipants.length} Teilnehmende</strong></div><div className="crew-grid">{activeParticipants.map(p=><div key={p.id} className={p.status}><i/ ><b>{p.callsign}</b><small>{p.status==='connected'?'verbunden':'getrennt'}</small><button aria-label={`${p.callsign} entfernen`} onClick={()=>window.confirm(`${p.callsign} entfernen?`)&&repo.remove(p.id)}><Trash2/></button></div>)}</div>{!activeParticipants.length&&<p>Noch ist niemand beigetreten.</p>}<div className="ready"><Radio/><strong>{ready} von {activeParticipants.length} bereit</strong><details><summary>Fehlende Rufzeichen</summary>{missing.map(p=><span key={p.id}>{p.callsign}</span>)}</details></div></article></div>{session.status==='lobby'&&<button className="mission-action" onClick={begin}><Play/> Mission beginnen</button>}{session.status==='active'&&<section className="active-placeholder"><Check/><p>Die Missionssitzung ist aktiv. Die Storyoberfläche wird im nächsten Entwicklungsschritt angebunden.</p><button onClick={finish}>Mission abschließen</button></section>}{session.status==='completed'&&<div className="archive-actions"><p>Diese Sitzung ist abgeschlossen und bleibt als Ergebnis erhalten.</p><button onClick={create}>Mission erneut starten</button></div>}{error&&<p className="mission-error" role="alert">{error}</p>}</main>
}
